#!/usr/bin/python3
#
import quixote
quixote.enable_ptl()
from quixote.publish import Publisher
from wsgiref.simple_server import make_server
import argparse
import frontend, auth, bbb, indico, config

def load_configs():
    cdir = options.config
    config.load_config(cdir)
    auth.load_users(cdir)
    bbb.load_config(cdir)
    indico.load_timetable()
    frontend.load_track_colors(cdir)

class wsgi_pub(Publisher):
    is_thread_safe = True

    def __init__(self, *args, **kwargs):
        Publisher.__init__(self, frontend.frontend())

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--config', dest = 'config', default = '.')
parser.add_argument('-p', '--port', dest = 'port', default = 8080, type = int)
options = parser.parse_args()

load_configs()
pub = wsgi_pub()
wsgi_app = quixote.get_wsgi_app() # Magically tied to pub
make_server('localhost', options.port, wsgi_app).serve_forever()
